---
# satellite-content vars

# Set wait_on_sync_minutes to zero to disable waiting
wait_on_sync_minutes: 120

# List lifecycle environments in order of promotion, making sure to
# specify prior environment. To create a new path, start with the prior
# set to "Library" and go from there.
sat_lifecycle:
  # General (for most systems)
  - env: "General_NonProd"
    prior: "Library"
  - env: "General_Prod"
    prior: "General_NonProd"
  # MySQL systems
  - env: "MySQL_NonProd"
    prior: "Library"
  - env: "MySQL_Prod"
    prior: "MySQL_NonProd"

# List content view details. View names must have no spaces.
# Repositories you want to include, should match the IDs output by
# hammer repository list --organization "{{ organization }}" and should be
# separated by commas. Take a look at satellite-setup/vars/main.yml for ordering
# Satellite 6.2 will fix the bug in hammer that allows you to specify repository names
# when adding repository sets. Will update the code after release to take that into account
sat_content_views:
  - name: "general-cv"
    description: "general - errata inclusions to 04.26.2016"
    env: [ 'General_NonProd', 'General_Prod' ]
    repo_ids: [ 3, 6, 7, 8, 11, 14, 17, 20, 23, 26, 29, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43 ]
  - name: "mysql-cv"
    description: "mysql - errata inclusions to 04.26.2016"
    env: [ 'MySQL_NonProd', 'MySQL_Prod' ]
    repo_ids: [ 2, 5, 7, 8, 10, 13, 16, 19, 22, 25, 28, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43 ]
  - name: "vagrant_boxes-cv"
    description: "vagrant_boxes - errata inclusions to 04.26.2016"
    env: [ 'Library' ]
    repo_ids: [ 1, 4, 7, 8, 9, 12, 15, 18, 21, 24, 27, 30, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43 ]

# Define package filters to apply to content views
# List repository IDs in repo_ids if application to specific repositories is desired
# E.g. | repo_ids: [ 1, 2, x ]
sat_content_package_filters:
  # Grab only needed Percona packages
  - name: "mysql-Percona_inclusions-filter"
    inclusion: yes
    type: rpm
    applytocv: "mysql-cv"
    repo_ids: [ 40, 41 ]
    packages:
      - "Percona-Server-client-56"
      - "Percona-Server-server-56"
      - "Percona-Server-shared-56"
      - "percona-toolkit"
      - "percona-xtrabackup"
      - "percona-zabbix-templates"
  # Grab only needed Percona packages
  - name: "vagrant_boxes-Percona_inclusions-filter"
    inclusion: yes
    type: rpm
    applytocv: "vagrant_boxes-cv"
    repo_ids: [ 40, 41 ]
    packages:
      - "Percona-Server-client-56"
      - "Percona-Server-server-56"
      - "Percona-Server-shared-56"
      - "percona-toolkit"
      - "percona-xtrabackup"
      - "percona-zabbix-templates"


# Define date filters to apply to content views
# List repository IDs in repo_ids if application to specific repositories is desired
# E.g. | repo_ids: [ 1, 2, x ]
sat_content_date_filters:
  - name: "general-dated_to_04262016-errata-filter"
    inclusion: no
    type: erratum
    applytocv: "general-cv"
    start_date: "2016-04-26"
    date_type: updated
    errata_types:
      - "security"
      - "enhancement"
      - "bugfix"
  - name: "mysql-dated_to_04262016-errata-filter"
    inclusion: no
    type: erratum
    applytocv: "mysql-cv"
    start_date: "2016-04-26"
    date_type: updated
    errata_types:
      - "security"
      - "enhancement"
      - "bugfix"

# Define activation keys
# All fields are required, with the exception of repo_overrides ~ which list repos to enable after key creation
sat_activation_keys:
  - name: "vagrant-ak"
    content_view: "vagrant_boxes-cv"
    lifecycle_env: "Library"
    releasever: "7Server"
    repo_overrides:
      - "rhel-7-server-satellite-tools-6.1-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-server-rhscl-7-rpms"
      - "rhel-7-server-optional-rpms"
      - "rhel-7-server-thirdparty-oracle-java-rpms"
      - "rhel-7-server-eus-satellite-tools-6.1-rpms"
      - "rhel-7-server-eus-optional-rpms"
      - "rhel-7-server-eus-supplementary-rpms"
      - "rhel-7-server-eus-rh-common-rpms"
      - "rhel-7-server-eus-rpms"
      - "rhel-7-server-eus-thirdparty-oracle-java-rpms"
      - "Your_Organization_EPEL_EPEL-7_x86_64"
      - "Your_Organization_GitLab_GitLab-7_x86_64"
      - "Your_Organization_MySQL_MySQL-Connectors-Community-7_x86_64"
      - "Your_Organization_Custom-Product_Custom-Repo-1"
      - "Your_Organization_Custom-Product_Custom-Repo-2"
      - "Your_Organization_Custom-Product_Custom-Repo-3"
      - "Your_Organization_Zabbix_Zabbix-30-7_x86_64"
  - name: "general_non-ak"
    content_view: "general-cv"
    lifecycle_env: "General_NonProd"
    releasever: "7.2"
    repo_overrides:
      - "rhel-7-server-satellite-tools-6.1-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-server-rhscl-7-rpms"
      - "rhel-7-server-optional-rpms"
      - "rhel-7-server-thirdparty-oracle-java-rpms"
      - "rhel-7-server-eus-satellite-tools-6.1-rpms"
      - "rhel-7-server-eus-optional-rpms"
      - "rhel-7-server-eus-supplementary-rpms"
      - "rhel-7-server-eus-rh-common-rpms"
      - "rhel-7-server-eus-rpms"
      - "rhel-7-server-eus-thirdparty-oracle-java-rpms"
      - "Your_Organization_EPEL_EPEL-7_x86_64"
      - "Your_Organization_GitLab_GitLab-7_x86_64"
      - "Your_Organization_Custom-Product_Custom-Repo-1"
      - "Your_Organization_Custom-Product_Custom-Repo-2"
      - "Your_Organization_Custom-Product_Custom-Repo-3"
      - "Your_Organization_Zabbix_Zabbix-30-7_x86_64"
  - name: "general_prod-ak"
    content_view: "general-cv"
    lifecycle_env: "General_Prod"
    releasever: "7.2"
    repo_overrides:
      - "rhel-7-server-satellite-tools-6.1-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-server-rhscl-7-rpms"
      - "rhel-7-server-optional-rpms"
      - "rhel-7-server-thirdparty-oracle-java-rpms"
      - "rhel-7-server-eus-satellite-tools-6.1-rpms"
      - "rhel-7-server-eus-optional-rpms"
      - "rhel-7-server-eus-supplementary-rpms"
      - "rhel-7-server-eus-rh-common-rpms"
      - "rhel-7-server-eus-rpms"
      - "rhel-7-server-eus-thirdparty-oracle-java-rpms"
      - "Your_Organization_EPEL_EPEL-7_x86_64"
      - "Your_Organization_GitLab_GitLab-7_x86_64"
      - "Your_Organization_Custom-Product_Custom-Repo-1"
      - "Your_Organization_Custom-Product_Custom-Repo-2"
      - "Your_Organization_Custom-Product_Custom-Repo-3"
      - "Your_Organization_Zabbix_Zabbix-30-7_x86_64"
  - name: "mysql_non-ak"
    content_view: "mysql-cv"
    lifecycle_env: "MySQL_NonProd"
    releasever: "7.1"
    repo_overrides:
      - "rhel-7-server-satellite-tools-6.1-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-server-rhscl-7-rpms"
      - "rhel-7-server-optional-rpms"
      - "rhel-7-server-thirdparty-oracle-java-rpms"
      - "rhel-7-server-eus-satellite-tools-6.1-rpms"
      - "rhel-7-server-eus-optional-rpms"
      - "rhel-7-server-eus-supplementary-rpms"
      - "rhel-7-server-eus-rh-common-rpms"
      - "rhel-7-server-eus-rpms"
      - "rhel-7-server-eus-thirdparty-oracle-java-rpms"
      - "Your_Organization_EPEL_EPEL-7_x86_64"
      - "Your_Organization_MySQL_MySQL-Connectors-Community-7_x86_64"
      - "Your_Organization_Custom-Product_Custom-Repo-2"
      - "Your_Organization_Custom-Product_Custom-Repo-3"
      - "Your_Organization_Percona_Percona-7_x86_64"
      - "Your_Organization_Percona_Percona-7_noarch"
      - "Your_Organization_Zabbix_Zabbix-30-7_x86_64"
  - name: "mysql_prod-ak"
    content_view: "mysql-cv"
    lifecycle_env: "MySQL_Prod"
    releasever: "7.1"
    repo_overrides:
      - "rhel-7-server-satellite-tools-6.1-rpms"
      - "rhel-7-server-extras-rpms"
      - "rhel-server-rhscl-7-rpms"
      - "rhel-7-server-optional-rpms"
      - "rhel-7-server-thirdparty-oracle-java-rpms"
      - "rhel-7-server-eus-satellite-tools-6.1-rpms"
      - "rhel-7-server-eus-optional-rpms"
      - "rhel-7-server-eus-supplementary-rpms"
      - "rhel-7-server-eus-rh-common-rpms"
      - "rhel-7-server-eus-rpms"
      - "rhel-7-server-eus-thirdparty-oracle-java-rpms"
      - "Your_Organization_EPEL_EPEL-7_x86_64"
      - "Your_Organization_MySQL_MySQL-Connectors-Community-7_x86_64"
      - "Your_Organization_Custom-Product_Custom-Repo-2"
      - "Your_Organization_Custom-Product_Custom-Repo-3"
      - "Your_Organization_Percona_Percona-7_x86_64"
      - "Your_Organization_Percona_Percona-7_noarch"
      - "Your_Organization_Zabbix_Zabbix-30-7_x86_64"

# Bucket name to pull custom rpms from... translates to
# https://s3.amazonaws.com/{{ sat_s3bucket }}/...
# RPM packages that are in this bucket have to be publicly accessible
sat_s3bucket: "my_satellite_rpm_bucket"

# Name of the custom product that you will upload conent to
sat_custom_product: "Custom-Product"

# List out package names and what repo to add them into, for the "Custom-Product" product
# within Satellite. We have to do this since we can't obtain a listing until
# Ansible 2.x
sat_custom_content:
  - name: "Custom-Repo-1"
    rpms:
      - "gitlab-ee-8.4.4-ee.0.el7.x86_64.rpm"
      - "gitlab-ee-8.6.5-ee.0.el7.x86_64.rpm"
  - name: "Custom-Repo-2"
    rpms:
      - "splunk-6.3.0-aa7d4b1ccb80-linux-2.6-x86_64.rpm"
      - "splunkforwarder-6.3.0-aa7d4b1ccb80-linux-2.6-x86_64.rpm"
  - name: "Custom-Repo-3"
    rpms:
      - "rh-amazon-rhui-client-2.2.123-2.el7.noarch.rpm"
