#!/bin/bash
# Refresh current subscription from .csv file generated by Ansible

INVFILE="$1"
LOGFILE="${HOME}/content_host_resubscription.log"

rm -f ${LOGFILE}
touch ${LOGFILE}

while read line; do
    NAME=`echo "${line}" | awk -F"," '{ print $1 }'`
    HOST=`echo "${line}" | awk -F"," '{ print $2 }'`
    ACTKEY=`echo "${line}" | awk -F"," '{ print $4 }'`
    SSHKEY=`echo "${line}" | awk -F"," '{ print $12 }'`.pem
    echo "Refreshing subscription on ${NAME}:"
    echo "ssh -t -t -i ${HOME}/.ssh/${SSHKEY} ${HOST} \"sudo /bin/subscription-manager refresh\"" | sh
    echo
done < $INVFILE | tee -a ${LOGFILE}