---
# ansible-satellite | Satellite 6.x Orchestration
- hosts: old_satellite
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
  gather_facts: no

  tasks:
    - set_fact: 
        inventory_content: []

    - name: ":::: Get organizations ::::"
      import_tasks: ./roles/satellite-content/tasks/get_orgs.yml
    
    - name: ":::: Create content inventory ::::"
      include_tasks: ./roles/satellite-content/tasks/create_content_inventory.yml
      with_items: "{{ organizations_list }}"
      vars:
        node:
          organization: "{{ item }}"

    - set_fact: 
        inventory_satellite: "{{ inventory_content }}"
        inventory_content: []

    - name: ":::: Get list of all activation keys ::::"
      include_tasks: ./roles/satellite-content/tasks/get_activation_keys_for_org.yml
      with_items: "{{ inventory_satellite }}"
      vars:
        organization: "{{ item.organization }}"

    - set_fact: 
        inventory_satellite: "{{ inventory_content }}"
        inventory_content: []

    - name: ":::: Get Host and Key subscriptions ::::"
      include_tasks: ./roles/satellite-content/tasks/get_nodes_for_keys.yml
      with_items: "{{ inventory_satellite }}"
      vars:
        organization: "{{ item.organization }}"
        activation_key: "{{ item.activationkey }}"

    - set_fact: 
        inventory_satellite: "{{ inventory_content }}"
        inventory_content: []

    - name: ":::: Create content inventory file ::::"
      include_tasks: ./roles/satellite-content/tasks/create_content_inventory_file.yml 
      vars:
        inventory_content: "{{ inventory_satellite }}"
      with_items: "{{ inventory_satellite }}"

- hosts: localhost
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
    - group_vars/inventory_content.yml
  gather_facts: yes
  
  tasks:

     # create dynamic groups to define variables
    - group_by: 
        key: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

    - set_fact: 
        ak: "{{ ansible_distribution }}-{{ ansible_distribution_version | truncate(1, True, '') }}"

    - name: ":::: Get repos for host ::::"
      include_tasks: roles/satellite-clients/tasks/client_get_enable_repos.yml

    - name: ":::: Unregister host ::::"
      include_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
      vars:
        satellite: "{{ groups['old_satellite'][0] }}"
    
    - name: ":::: Register host ::::"
      include_tasks: ./roles/satellite-clients/tasks/client_unsubscribe.yml
      vars:
        satellite: "{{ groups['satellite'][0] }}"
        activationkey: "{{ groups[ak] }}"
