---
# ansible-satellite | Maintenance Playbook

- hosts: satellite6-server-prod
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/secrets.yml
  gather_facts: yes
  roles:
    # satellite-maintenance | Perform post-installation tasks
    - role: satellite-maintenance
      # upload_rpms: no
      # autoupdate_content_views: no
      # promote_content_views_to_prod: no
      # slack_pubpromo_notify: yes
      # security_tweaks: no
      # restart_services: no