---
# ansible-satellite | Satellite 6.x Orchestration

- hosts: satellite6-server-prod
  become: yes
  vars_files:
    - group_vars/satellite.yml
    - group_vars/secrets.yml
  gather_facts: yes
  roles:
    # satellite-auth | Define users and assign them roles
    - role: satellite-auth
      ldap_refresh: yes