---
# Set up Docker repositories

  # Create Docker products
  - name: Create Docker products
    command: >
      /bin/hammer product create
      --organization "{{ initial_org }}"
      --name "{{ item.name }}"
    register: create_docker_prod
    with_items: sat_docker_products
    failed_when: >
      create_docker_prod.rc != 0
      and create_docker_prod.rc != 65
    changed_when: >
      create_docker_prod.rc == 0

  # Create Docker repositories for the products
  - name: Create additional Docker repositories
    command: >
      /bin/hammer repository create
      --organization "{{ initial_org }}"
      --product "{{ item.0.name }}"
      --name "{{ item.1.name }}"
      --content-type "docker"
      --url "{{ item.1.url }}"
      --docker-upstream-name "{{ item.1.upstream }}"
      {{ item.1.options }}
    register: create_docker_repo
    with_subelements:
      - sat_docker_products
      - repos
    failed_when: >
      create_docker_repo.rc != 0
      and create_docker_repo.rc != 65
    changed_when: >
      create_docker_repo.rc == 0